allowBuilds:
  '@google/genai': set this to true or false
  electron: true
  electron-winstaller: true
  esbuild: true
  lefthook: true
  protobufjs: set this to true or false

minimumReleaseAgeExclude:
  - '@tangramino/base-editor@0.1.2'
  - '@tangramino/engine@0.1.2'
  - '@tangramino/flow-editor@0.1.2'
  - '@tangramino/react@0.1.2'

packages:
  - apps/*
  - packages/*
